//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSETEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COURSETEST()
        {
            this.TESTQUESTIONs = new HashSet<TESTQUESTION>();
            this.TESTRESULTs = new HashSet<TESTRESULT>();
        }
    
        public int test_id { get; set; }
        public int part_id { get; set; }
        public string test_name { get; set; }
        public int mandatory { get; set; }
        public System.TimeSpan test_maxtime { get; set; }
        public int total_score { get; set; }
        public int score_to_pass { get; set; }
    
        public virtual COURSEPART COURSEPART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTQUESTION> TESTQUESTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTRESULT> TESTRESULTs { get; set; }
    }
}
