//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseTest()
        {
            this.TestQuestions = new HashSet<TestQuestion>();
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int test_id { get; set; }
        public int resource_id { get; set; }
        public int mandatory { get; set; }
        public System.TimeSpan test_maxtime { get; set; }
        public int total_score { get; set; }
        public int score_to_pass { get; set; }
        public Nullable<int> display_type { get; set; }
        public Nullable<int> max_attempt { get; set; }
        public int shuffle { get; set; }
    
        public virtual CourseResource CourseResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
