//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSERESOURCE
    {
        public int resource_id { get; set; }
        public int part_id { get; set; }
        public string resource_name { get; set; }
        public int resource_type { get; set; }
        public string resource_filename { get; set; }
        public int allow_download { get; set; }
    
        public virtual COURSEPART COURSEPART { get; set; }
    }
}
