//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELEARNINGEntities : DbContext
    {
        public ELEARNINGEntities()
            : base("name=ELEARNINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<COURSEPART> COURSEPARTs { get; set; }
        public virtual DbSet<COURSERESOURCE> COURSERESOURCEs { get; set; }
        public virtual DbSet<COURSEREVIEW> COURSEREVIEWs { get; set; }
        public virtual DbSet<COURSETEST> COURSETESTs { get; set; }
        public virtual DbSet<REGISTER> REGISTERs { get; set; }
        public virtual DbSet<TESTQUESTION> TESTQUESTIONs { get; set; }
        public virtual DbSet<TESTRESULT> TESTRESULTs { get; set; }
    }
}
