//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTER()
        {
            this.COURSEREVIEWs = new HashSet<COURSEREVIEW>();
            this.TESTRESULTs = new HashSet<TESTRESULT>();
        }
    
        public int register_id { get; set; }
        public int learner_id { get; set; }
        public int course_id { get; set; }
        public System.DateTime registered_date { get; set; }
        public int register_status { get; set; }
        public Nullable<int> completion_score { get; set; }
        public string course_certificate { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual COURSE COURSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSEREVIEW> COURSEREVIEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTRESULT> TESTRESULTs { get; set; }
    }
}
