//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTRESULT
    {
        public int result_id { get; set; }
        public int register_id { get; set; }
        public int test_id { get; set; }
        public int test_ordinal { get; set; }
        public int test_score { get; set; }
        public System.TimeSpan test_time { get; set; }
        public int is_passed { get; set; }
    
        public virtual COURSETEST COURSETEST { get; set; }
        public virtual REGISTER REGISTER { get; set; }
    }
}
