//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTQUESTION
    {
        public int question_id { get; set; }
        public int test_id { get; set; }
        public string question_description { get; set; }
        public int question_type { get; set; }
        public string choices { get; set; }
        public string answer { get; set; }
        public int score { get; set; }
    
        public virtual COURSETEST COURSETEST { get; set; }
    }
}
